term.clear(); term.setCursorPos(1,1)
print("NEXUS SYSTEM INFORMATION")
print("Kernel: "..NEXUS.version)
print("Computer ID: "..tostring(os.getComputerID()))
print("Label: "..tostring(os.getComputerLabel()))
print("Uptime: "..string.format("%.1fs",os.clock()-NEXUS.bootTime))
print("Storage used: "..tostring(fs.getSize("/")))
print("Storage free: "..tostring(fs.getFreeSpace("/")))
print("Devices: "..tostring(#peripheral.getNames()))
print("\nPress any key..."); os.pullEvent("key")
